# Generated by Django 4.0.5 on 2022-10-11 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=31)),
                ('text', models.TextField()),
                ('posted', models.DateTimeField(default=datetime.datetime(2022, 10, 11, 13, 57, 47, 411597, tzinfo=utc))),
            ],
        ),
    ]
