# Generated by Django 4.0.5 on 2022-10-11 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comment_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 14, 3, 32, 409402, tzinfo=utc)),
        ),
    ]
