# Generated by Django 4.0.5 on 2022-10-11 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
