# Generated by Django 4.0.5 on 2022-10-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comment_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='str_date',
            field=models.CharField(default='cucumber', max_length=31),
        ),
    ]
