# Generated by Django 4.0.5 on 2022-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_comment_str_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='str_date',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
