# Generated by Django 4.0.5 on 2022-10-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alumni_wall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='user_stuff',
        ),
        migrations.AddField(
            model_name='wall',
            name='font',
            field=models.TextField(default='foo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wall',
            name='grid',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wall',
            name='link',
            field=models.URLField(default='foo.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wall',
            name='username',
            field=models.CharField(default='foo', max_length=31),
            preserve_default=False,
        ),
    ]
