# Generated by Django 4.0.5 on 2022-10-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_wall_user_stuff_wall_font_wall_grid_wall_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='number',
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(default='jude@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
